spring.application.name=franchise-api
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/franchisedb}
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.orm.jpa.autoconfigure.HibernateJpaAutoConfiguration
server.port=8080
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
